import * as Redux from 'redux'
import PropTypes from 'prop-types'
import React from "react"
import { connect } from 'react-redux'

const todo = (state, action) =>{
  switch(action.type) {
    case 'ADD_TODO':
      return {
          id: action.id,
          text: action.text,
          completed: false
        }
    case 'TOGGLE_TODO':
      if (state.id !== action.id) {
        return state
      }
      return Object.assign({}, state, {
        completed: !state.completed
      })
    default:
      return state
  }
}

const todos = (state=[], action) => {
  switch (action.type) {
    case 'ADD_TODO':
      return state.slice().concat(
        todo(undefined, action)
      )
    case 'TOGGLE_TODO':
      return state.map(t => todo(t, action))
    default:
      return state
  }
}

const visibilityFilter = (
  state='SHOW_ALL',
  action
) => {
  switch (action.type) {
    case 'SET_VISIBILITY_FILTER':
      return action.filter
    default:
      return state
  }
}

const combineReducers = (reducers) => {
  return (state = {}, action) => {
    return Object.keys(reducers).reduce((nextState, key) => {
      nextState[key] = reducers[key](state[key], action)
      return nextState
    }, {})
  }
}

const { createStore } = Redux

const todoApp = combineReducers({
  todos,
  visibilityFilter
})

const OptionalLink = ({active, filter, onClick, children}) => {
  if (active) {
    return (
      <span>{children}</span>
    )
  }
  return (
    <a href={'#'}
       onClick={e => {
         e.preventDefault()
         onClick()
       }}>
      {children}
    </a>
  )
}

// container component, not a part of the presentation layer
class FilterLink extends React.Component {
  componentDidMount() {
    // executed once
    const { store } = this.context
    this.unsubscribe = store.subscribe(() => this.forceUpdate())
  }
  componentWillUnmount() {
    this.unsubscribe()
  }

  render() {
    const { store } = this.context
    return (
      <OptionalLink
        children={this.props.children}
        filter={this.props.filter}
        active={
          store.getState().visibilityFilter ===
          this.props.filter
        }
        onClick={() => {
          store.dispatch({
            type: 'SET_VISIBILITY_FILTER',
            filter: this.props.filter
          })
        }}
      />
    )
  }
}

FilterLink.contextTypes = {
  store: PropTypes.object
}

const filterTodos = (todos, filter) => {
  return todos.filter(todo => {
    switch (filter) {
      case 'SHOW_ALL':
        return true
      case 'SHOW_COMPLETED':
        return todo.completed
      case 'SHOW_ACTIVE':
        return !todo.completed
      default:
        return true
    }
  })
}

const Todo = ({text, completed, onClick}) => (
    <li
        style={{
          textDecoration: completed ? 'line-through' : 'none'
        }}
        onClick={onClick}>
      {text}
    </li>
)

const TodoList = ({todos, onTodoClick}) => (
  <ul>
    {todos.map(t => (
      // adds props from stored objec to the react component:
      // Object.assign(new Todo(), t, {onClick: () => {}})
      <Todo key={t.id}
            {...t}
            onClick={() => onTodoClick(t.id)}
      />
    ))}
  </ul>
)

const mapStateToProps = (state) => {
  return {
    todos: filterTodos(
      state.todos,
      state.visibilityFilter
    ),
    visibilityFilter: state.visibilityFilter
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    onTodoClick: (id) => {
      dispatch({
        type: 'TOGGLE_TODO',
        id: id
      })
    },

  }
}

const VisibleTodoList = connect(
  mapStateToProps,
  mapDispatchToProps
)(TodoList)

// Now generated by ReactRedux#connect function
//
// class VisibleTodoList extends React.Component {
//   componentDidMount() {
//     const { store } = this.context
//     this.unsubscribe = store.subscribe(() => {
//       this.forceUpdate()
//     })
//   }
//   componentWillUnmount() {
//     this.unsubscribe()
//   }
//   render() {
//     const { store } = this.context
//     const state = store.getState()
//     return (
//       <TodoList
//         todos={filterTodos(
//           state.todos,
//           state.visibilityFilter
//         )}
//       />
//     )
//   }
// }
//
// VisibleTodoList.contextTypes = {
//   store: PropTypes.object
// }

// (props, context): context = {store: ... }
const AddTodo = (props, { store }) => {
  let input
  const onAddClick = (text) => {
    store.dispatch({
      type: 'ADD_TODO',
      id: nextTodoId++,
      text
    })
  }
  return (
    <div>
      <input ref={node => {input = node}} type="text" />
      <button onClick={() => {
        onAddClick(input.value)
        input.value = ''  // set to empty string after clicking the button
      }}>
        Add todo
      </button>
    </div>
  )
}

AddTodo.contextTypes = {
  store: PropTypes.object
}

const Footer = () => (
  <p>
    <FilterLink filter='SHOW_ALL'>
      All
    </FilterLink>
    <br/>
    <FilterLink filter='SHOW_COMPLETED'>
      Completed
    </FilterLink>
    <br/>
    <FilterLink filter='SHOW_ACTIVE'>
      Active
    </FilterLink>
  </p>
)

let nextTodoId = 0
const TodoApp = () => (
  <div>
    <h1>Todo app</h1>
    <AddTodo />
    <VisibleTodoList />
    <Footer />
  </div>
)

// class Provider extends React.Component {
//   getChildContext() {
//     return {
//       store: this.props.store
//     }
//   }
//   render() {
//     return this.props.children
//   }
// }
//
// Provider.childContextTypes = {
//   store: PropTypes.object
// }


const todoStore = createStore(todoApp)
todoStore.subscribe(() => {console.log(todoStore.getState())})

export {
  TodoApp,
  todos,
  todoStore,
}